### ISSUE TITLE
Update Readme? Directories required manual creation

### ISSUE THREAD

**Issue by mkuplens** [kjake/freenas-iocage-unifi#1]
This is awesome - thanks for sharing!

Things seemed to rather fall apart when the script was run without the various directories in place (portsnap + unifi + subdirectories). The instructions re. dehyrated also weren't quite as clear until a third reading connected the dots.

It might be worth tweaking the readme to include a step to create the directories.

**Comment by kjake** [comment]
Hey there, thanks for taking the time to comment on this.

I added mkdir commands to the jail script so that the directories are created - a user now only need to define a base path (${JAIL_PATH}).

I also just committed some bug fixes for some other issues that could have led to some trouble for an initial install (I never fully deleted my setup and started from scratch to test this).

**Comment by kjake** [comment]
I've re-read the README, are there specifics on the Let's Encrypt part that you got stuck on? The DNS overloading is probably the trickiest concept to get unless you're familiar with managing DNS a lot.
